/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.main.java.Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.main.java.Controlador.Controlador;
import src.main.java.Controlador.DAO;

/**
 *
 * @author Mauricio
 */
public class Consultar extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Consultar() {
        initComponents();
        setLocationRelativeTo(null);
        LimpiarCampos();
        mostrarQuesos();
        rellenarCombobox();
               
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/QUESO-INGRESO.png"));
        return retValue;
    }
    public final void LimpiarCampos(){

        tipo_queso.setSelectedIndex(0);
        textura.setSelectedIndex(0);
        gusto.setSelectedIndex(0);
        tratamiento.setSelectedIndex(0);
        tipo_leche.setSelectedIndex(0);
        contenido_graso.setSelectedIndex(0);
        maduracion.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        
        mostrarQuesos();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        JPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textura = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        gusto = new javax.swing.JComboBox<>();
        tipo_queso = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tratamiento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tipo_leche = new javax.swing.JComboBox<>();
        contenido_graso = new javax.swing.JComboBox<>();
        maduracion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONSULTAR");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanel.setBackground(new java.awt.Color(250, 204, 0));
        JPanel.setToolTipText("CONSULTAR");
        JPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Consultar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 180, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        JPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 190, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Átras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        JPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 310, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de leche:");
        JPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tratamiento de la leche:");
        JPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        textura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        JPanel.add(textura, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 150, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Contenido graso:");
        JPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        gusto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        JPanel.add(gusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 150, -1));

        tipo_queso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        tipo_queso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_quesoActionPerformed(evt);
            }
        });
        JPanel.add(tipo_queso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Maduración:");
        JPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        tratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        JPanel.add(tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Textura:");
        JPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAR");
        JPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1330, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de queso:");
        JPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Gusto:");
        JPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 840, 320));

        tipo_leche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        tipo_leche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_lecheActionPerformed(evt);
            }
        });
        JPanel.add(tipo_leche, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 150, -1));

        contenido_graso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        contenido_graso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenido_grasoActionPerformed(evt);
            }
        });
        JPanel.add(contenido_graso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 150, -1));

        maduracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        maduracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maduracionActionPerformed(evt);
            }
        });
        JPanel.add(maduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 150, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Seleccione un filtro para su consulta");
        JPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 280, -1));

        buttonGroup1.add(jRadioButton1);
        JPanel.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 30, -1));

        buttonGroup1.add(jRadioButton2);
        JPanel.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 30, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        JPanel.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 30, -1));

        buttonGroup1.add(jRadioButton4);
        JPanel.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 30, -1));

        buttonGroup1.add(jRadioButton5);
        JPanel.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 30, -1));

        buttonGroup1.add(jRadioButton6);
        JPanel.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 30, -1));

        buttonGroup1.add(jRadioButton7);
        JPanel.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 30, -1));

        getContentPane().add(JPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String option = null, type = null;
        
        if(this.jRadioButton2.isSelected()){
            option = "tipo_queso";
            type = (String) tipo_queso.getSelectedItem();
        }
        
        if(this.jRadioButton3.isSelected()){
            option = "tipo_leche";
            type = (String) tipo_leche.getSelectedItem();
        }

        if(this.jRadioButton4.isSelected()){
            option = "contenido_materia_grasa";
            type = (String) contenido_graso.getSelectedItem();
        }

        if(this.jRadioButton5.isSelected()){
            option = "maduracion";
            type = (String) maduracion.getSelectedItem();
        }

        if(this.jRadioButton6.isSelected()){
            option = "textura";
            type = (String) textura.getSelectedItem();
        }

        if(this.jRadioButton7.isSelected()){
            option = "gusto";
            type = (String) gusto.getSelectedItem();
        }
        if(this.jRadioButton1.isSelected()){
            option = "tratamiento_leche";
            type = (String) tratamiento.getSelectedItem();
        }

        DAO consultar = new DAO();
        DefaultTableModel modelo = consultar.filtrarQuesos(option, type);
        jTable1.setModel(modelo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu menuPrincipal = new Menu();
        menuPrincipal.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tipo_quesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_quesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_quesoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tipo_lecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_lecheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_lecheActionPerformed

    private void contenido_grasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenido_grasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contenido_grasoActionPerformed

    private void maduracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maduracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maduracionActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    public void mostrarQuesos(){
    
        DAO consultar = new DAO();
        DefaultTableModel modelo = consultar.mostrarTodosLosQuesos();
        jTable1.setModel(modelo);
    }
    
    public void rellenarCombobox(){
        Controlador control;
        try {
            control = new Controlador();
            Object [] tipo_queso = control.TipoQuesoArray();
            Object [] tipo_leche = control.TipoLecheArray();
            Object [] contenido_grasa = control.materiaGrasaArray();
            Object [] maduraciont = control.TipoMaduracionArray();
            Object [] texturat = control.TipoTexturaArray();
            Object [] gustot = control.TipoIntensidadArray();
            Object [] tratamientot = control.TipoTratamientoArray();
            
            for (int i = 0; i < tipo_queso.length; i++) {
                String nameOfOption = tipo_queso[i].toString();
                this.tipo_queso.addItem(nameOfOption);
            }
            
            for (int i = 0; i < tipo_leche.length; i++) {
                String nameOfOption = tipo_leche[i].toString();
                this.tipo_leche.addItem(nameOfOption);
            }
            
            for (int i = 0; i < contenido_grasa.length; i++) {
                String nameOfOption = contenido_grasa[i].toString();
                this.contenido_graso.addItem(nameOfOption);
            }
            
            for (int i = 0; i < maduraciont.length; i++) {
                String nameOfOption = maduraciont[i].toString();
                this.maduracion.addItem(nameOfOption);
            }
            
            for (int i = 0; i < texturat.length; i++) {
                String nameOfOption = texturat[i].toString();
                this.textura.addItem(nameOfOption);
            }
            
            for (int i = 0; i < gustot.length; i++) {
                String nameOfOption = gustot[i].toString();
                this.gusto.addItem(nameOfOption);
            }
            
            for (int i = 0; i < tratamientot.length; i++) {
                String nameOfOption = tratamientot[i].toString();
                this.tratamiento.addItem(nameOfOption);
            }
            
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"No se pudieron rellenar los combobox");
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> contenido_graso;
    public javax.swing.JComboBox<String> gusto;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JComboBox<String> maduracion;
    public javax.swing.JComboBox<String> textura;
    public javax.swing.JComboBox<String> tipo_leche;
    public javax.swing.JComboBox<String> tipo_queso;
    public javax.swing.JComboBox<String> tratamiento;
    // End of variables declaration//GEN-END:variables
}
