/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.main.java.Vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.main.java.Controlador.Controlador;
import src.main.java.Controlador.DAO;

/**
 *
 * @author Mauricio
 */
public class Eliminar extends javax.swing.JFrame {
    
    /**
     * Creates new form Eliminar
     */
    public Eliminar() {
        initComponents();
        setLocationRelativeTo(null);
        LimpiarCampos();
        mostrarQuesos();
        rellenarCombobox();
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/QUESO-INGRESO.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        tipo_leche = new javax.swing.JComboBox<>();
        textura = new javax.swing.JComboBox<>();
        gusto = new javax.swing.JComboBox<>();
        tratamiento = new javax.swing.JComboBox<>();
        tipo_queso = new javax.swing.JComboBox<>();
        contenido_graso = new javax.swing.JComboBox<>();
        maduracion = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ELIMINAR");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 140, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 150, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Átras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tipo de leche:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tratamiento de la leche:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Contenido graso:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Maduración:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Textura:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ELIMINAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1340, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tipo de queso:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Gusto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 830, 580));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Consultar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 550, 140, -1));

        tipo_leche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        tipo_leche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_lecheActionPerformed(evt);
            }
        });
        jPanel1.add(tipo_leche, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 150, -1));

        textura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel1.add(textura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 150, -1));

        gusto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel1.add(gusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 150, -1));

        tratamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jPanel1.add(tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 150, -1));

        tipo_queso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        tipo_queso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_quesoActionPerformed(evt);
            }
        });
        jPanel1.add(tipo_queso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 150, -1));

        contenido_graso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        contenido_graso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contenido_grasoActionPerformed(evt);
            }
        });
        jPanel1.add(contenido_graso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 150, -1));

        maduracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        maduracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maduracionActionPerformed(evt);
            }
        });
        jPanel1.add(maduracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 150, -1));

        buttonGroup1.add(jRadioButton1);
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jPanel1.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jPanel1.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jPanel1.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Seleccione un filtro para su consulta:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents
        


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String idParaEliminar = JOptionPane.showInputDialog("¿Cuál es el id del queso que quiere eliminar?");
        JOptionPane.showMessageDialog(null,"Se borrará el queso con id: " + idParaEliminar);

        DAO eliminar = new DAO();
        eliminar.eliminarQueso(idParaEliminar);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String option = null, type = null;
        
        if(this.jRadioButton2.isSelected()){
            option = "tipo_queso";
            type = (String) tipo_queso.getSelectedItem();
        }
        
        if(this.jRadioButton3.isSelected()){
            option = "tipo_leche";
            type = (String) tipo_leche.getSelectedItem();
        }

        if(this.jRadioButton4.isSelected()){
            option = "contenido_materia_grasa";
            type = (String) contenido_graso.getSelectedItem();
        }

        if(this.jRadioButton5.isSelected()){
            option = "maduracion";
            type = (String) maduracion.getSelectedItem();
        }

        if(this.jRadioButton6.isSelected()){
            option = "textura";
            type = (String) textura.getSelectedItem();
        }

        if(this.jRadioButton7.isSelected()){
            option = "gusto";
            type = (String) gusto.getSelectedItem();
        }
        if(this.jRadioButton1.isSelected()){
            option = "tratamiento_leche";
            type = (String) tratamiento.getSelectedItem();
        }

        DAO consultar = new DAO();
        DefaultTableModel modelo = consultar.filtrarQuesos(option, type);
        jTable1.setModel(modelo);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Menu menuPrincipal = new Menu();
        menuPrincipal.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tipo_lecheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_lecheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_lecheActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        LimpiarCampos();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tipo_quesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_quesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_quesoActionPerformed

    private void contenido_grasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contenido_grasoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contenido_grasoActionPerformed

    private void maduracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maduracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maduracionActionPerformed

    public void mostrarQuesos(){
    
        DAO consultar = new DAO();
        DefaultTableModel modelo = consultar.mostrarTodosLosQuesos();
        jTable1.setModel(modelo);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public final void LimpiarCampos(){
        
        tipo_leche.setSelectedIndex(0);
        textura.setSelectedIndex(0);
        gusto.setSelectedIndex(0);
        tratamiento.setSelectedIndex(0);
        tipo_queso.setSelectedIndex(0);
        contenido_graso.setSelectedIndex(0);
        maduracion.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        mostrarQuesos();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
        
        
    }
    
    public void rellenarCombobox(){
        Controlador control;
        try {
            control = new Controlador();
            Object [] tipo_queso = control.TipoQuesoArray();
            Object [] tipo_leche = control.TipoLecheArray();
            Object [] contenido_grasa = control.materiaGrasaArray();
            Object [] maduraciont = control.TipoMaduracionArray();
            Object [] texturat = control.TipoTexturaArray();
            Object [] gustot = control.TipoIntensidadArray();
            Object [] tratamientot = control.TipoTratamientoArray();
            
            for (int i = 0; i < tipo_queso.length; i++) {
                String nameOfOption = tipo_queso[i].toString();
                this.tipo_queso.addItem(nameOfOption);
            }
            
            for (int i = 0; i < tipo_leche.length; i++) {
                String nameOfOption = tipo_leche[i].toString();
                this.tipo_leche.addItem(nameOfOption);
            }
            
            for (int i = 0; i < contenido_grasa.length; i++) {
                String nameOfOption = contenido_grasa[i].toString();
                this.contenido_graso.addItem(nameOfOption);
            }
            
            for (int i = 0; i < maduraciont.length; i++) {
                String nameOfOption = maduraciont[i].toString();
                this.maduracion.addItem(nameOfOption);
            }
            
            for (int i = 0; i < texturat.length; i++) {
                String nameOfOption = texturat[i].toString();
                this.textura.addItem(nameOfOption);
            }
            
            for (int i = 0; i < gustot.length; i++) {
                String nameOfOption = gustot[i].toString();
                this.gusto.addItem(nameOfOption);
            }
            
            for (int i = 0; i < tratamientot.length; i++) {
                String nameOfOption = tratamientot[i].toString();
                this.tratamiento.addItem(nameOfOption);
            }
            
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"No se pudieron rellenar los combobox");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> contenido_graso;
    public javax.swing.JComboBox<String> gusto;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JComboBox<String> maduracion;
    public javax.swing.JComboBox<String> textura;
    public javax.swing.JComboBox<String> tipo_leche;
    public javax.swing.JComboBox<String> tipo_queso;
    public javax.swing.JComboBox<String> tratamiento;
    // End of variables declaration//GEN-END:variables
}
