/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package src.main.java.Vista;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Mauricio
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/QUESO-INGRESO.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ingresarBTN = new javax.swing.JButton();
        consultarBTN = new javax.swing.JButton();
        modificarBTN = new javax.swing.JButton();
        eliminarBTN = new javax.swing.JButton();
        cerrarBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENÚ");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel1.setText("BIENVENIDO AL MENÚ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("A continuación selecciona una opción:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/QUESO-INGRESO.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 230, 210));

        ingresarBTN.setBackground(new java.awt.Color(0, 0, 0));
        ingresarBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ingresarBTN.setForeground(new java.awt.Color(255, 255, 255));
        ingresarBTN.setText("Ingresar");
        ingresarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(ingresarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 140, -1));

        consultarBTN.setBackground(new java.awt.Color(0, 0, 0));
        consultarBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        consultarBTN.setForeground(new java.awt.Color(255, 255, 255));
        consultarBTN.setText("Consultar");
        consultarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(consultarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 140, -1));

        modificarBTN.setBackground(new java.awt.Color(0, 0, 0));
        modificarBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        modificarBTN.setForeground(new java.awt.Color(255, 255, 255));
        modificarBTN.setText("Modificar");
        modificarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(modificarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, -1));

        eliminarBTN.setBackground(new java.awt.Color(0, 0, 0));
        eliminarBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        eliminarBTN.setForeground(new java.awt.Color(255, 255, 255));
        eliminarBTN.setText("Eliminar");
        eliminarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(eliminarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, -1));

        cerrarBTN.setBackground(new java.awt.Color(255, 0, 0));
        cerrarBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cerrarBTN.setForeground(new java.awt.Color(255, 255, 255));
        cerrarBTN.setText("Cerrar sesión");
        cerrarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarBTNActionPerformed(evt);
            }
        });
        jPanel1.add(cerrarBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBTNActionPerformed
        // TODO add your handling code here:
        Ingresar ingreso = new Ingresar();
        ingreso.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_ingresarBTNActionPerformed

    private void consultarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBTNActionPerformed
        // TODO add your handling code here:
        Consultar consulta = new Consultar();
        consulta.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_consultarBTNActionPerformed

    private void modificarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBTNActionPerformed
        // TODO add your handling code here:
        Modificar modifica = new Modificar();
        modifica.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_modificarBTNActionPerformed

    private void eliminarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBTNActionPerformed
        // TODO add your handling code here:
        Eliminar elimina = new Eliminar();
        elimina.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_eliminarBTNActionPerformed

    private void cerrarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarBTNActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_cerrarBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cerrarBTN;
    public javax.swing.JButton consultarBTN;
    public javax.swing.JButton eliminarBTN;
    public javax.swing.JButton ingresarBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton modificarBTN;
    // End of variables declaration//GEN-END:variables
}
